---
galaxy_info:
  author: flavien BOUGEOIS
  description: Installs InfluxDB using Docker Compose
  license: license (MIT)
  min_ansible_version: 2.4
  platforms:
  - name: Ubuntu
    versions:
    - bionic
    - focal
dependencies: []